#For Ubuntu 16.04
echo Begin setup ....
sudo apt-get update
sudo apt-get -y upgrade
echo Installing git ...
sudo apt install git
echo Python3 version is:
python3 -V
echo Installing pip3 ...
sudo apt-get install -y python3-pip -y
sudo apt install python-pip
echo Installing ag ...
sudo apt install silversearcher-ag
echo Removing packages that are no longer required ...
sudo apt autoremove -y
